Blog/Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# Importa las vistas necesarias
from .views import index

urlpatterns = [
    # Rutas principales del proyecto
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    
    # Rutas de las aplicaciones
    path('post/', include('apps.Post.urls')),
    path('comentario/', include('apps.Comment.urls')),
    path('perfil/', include('apps.Perfiles.urls')),
]

# Configuración para servir archivos estáticos y de medios en desarrollo
# Asegúrate de que esto solo se ejecute cuando DEBUG sea True
if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

Blog/apps/Perfiles/urls.py
from django.urls import path
from .views import SignUpView, UsuarioView, AdminView
from .views import Login

app_name = 'apps.Perfiles'

urlpatterns = [
    path("usuario/", UsuarioView.as_view(), name="usuario"),
    path("admin/", AdminView.as_view(), name="admin"),
    path('registrarse/',SignUpView.as_view(), name='registrarse'),
    path('login/',Login.as_view(), name='login'),
]

Blog/apps/Post/urls.py
from django.urls import path
from .views import CrearPost, ActualizarPost, EliminarPost, ListarPost , DetallarPost
from .views import AgregarGenero, ActualizarGenero, EliminarGenero
from .views import AgregarPlataforma, ActualizarPlataforma, EliminarPlataforma


app_name = 'post'

urlpatterns = [
    path("agregar_genero/", AgregarGenero.as_view(), name="agregar_genero"),
    path("actualizar_genero/", ActualizarGenero.as_view(), name="actualizar_genero"),
    path("eliminar_genero/", EliminarGenero.as_view(), name="eliminar_genero"),

    path("agregar_plataforma/", AgregarPlataforma.as_view(), name="agregar_plataforma"),
    path("actualizar_plataforma/", ActualizarPlataforma.as_view(), name="actualizar_plataforma"),
    path("eliminar_plataforma/", EliminarPlataforma.as_view(), name="eliminar_plataforma"),

    path('', ListarPost.as_view(),name='posts'),
    path('agregar/', CrearPost.as_view(),name='agregar_post'),
    path('actualizar/<int:pk>/', ActualizarPost.as_view(), name='actualizar_post'),
    path('eliminar/<int:pk>',EliminarPost.as_view(),name='eliminar_post'),
    path('<int:id>/',DetallarPost.as_view(),name='post_individual'),
]

Blog/apps/Perfiles/models.py
from django.db import models
from django.contrib.auth.models import User


class Perfil(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    imagen_perfil = models.ImageField(upload_to='perfiles/', blank=True, null=True)
    biografia = models.TextField(null=True, blank=True)

    def __str__(self):
        return f'Perfil de {self.usuario.username}'
    
    def delete(self, using = None, keep_parents = False):
        self.imagen_perfil.delete(self.imagen_perfil.name)
        super().delete()

Blog/apps/Perfiles/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    class Meta:
        model = User 
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',)
        

Blog/apps/Perfiles/views.py
from django.urls import reverse_lazy
from django.views.generic import FormView
from .forms import SignUpForm
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

class UsuarioView(TemplateView):
    template_name = 'perfiles/usuario.html'

class AdminView(TemplateView):
    template_name = 'perfiles/admin.html'


# ----------registrar usuarios----------

class SignUpView(FormView):
    template_name = 'perfiles/registrarse.html'
    form_class = SignUpForm
    success_url = reverse_lazy('apps.Perfiles:login')


    def form_valid(self, form):
        form.save()
        return super().form_valid(form)
    

#----------Login---------------------


class Login(auth_views.LoginView):
    template_name = 'perfiles/login.html'

Blog/templates/perfiles/admin.html
{% extends "base.html" %} 
{% load static %} 

{% block titulo %}
<title>Admin</title>
{% endblock %} 

{% block header %} 
{% include "partes/header.html" %}
{%endblock%} 

{% block contenido %}

    <h2>Panel del Administrador</h2>

    <a href="{% url 'post:agregar_genero' %}">Nuevo Genero</a>
    <a href="{% url 'post:agregar_plataforma' %}">Nueva Plataforma</a>
    <a href="{% url 'post:agregar_post' %}">Nuevo Post</a>

    <hr />

    <h3>Lista de todos los Generos</h3>
    <ul>
        {% for genero in generos %}
            <li>
                <h4>{{genero.id}} {{genero.genero}}</h4>
                <a href="{% url 'post:actualizar_genero' genero.id %}">Editar</a>
                <a href="{% url 'post:eliminar_genero' genero.id %}">Eliminar</a>
            </li>
        {% endfor %}
    </ul>
    <hr />

    <h3>Lista de todos las plataformas</h3>
    <ul>
        {% for plataforma in plataformas %}
            <li>
                <h4>{{plataforma.id}} {{plataforma.plataforma}}</h4>
                <a href="{% url 'post:actualizar_plataforma' plataforma.id %}">Editar</a>
                <a href="{% url 'post:eliminar_plataforma' plataforma.id %}">Eliminar</a>
            </li>
        {% endfor %}
    </ul>
    <hr />

  

    <h3>Lista de todos los Posts</h3>
    <ul>
        {% for post in posts %}
            <li>
                <h4>{{post.id}} {{post.titulo}} - {{post.fecha}}</h4>
                <a href="{% url 'post:post_individual' post.id %}">Ver</a>
                <a href="{% url 'post:actualizar_post' post.id %}">Editar</a>
                <a href="{% url 'post:eliminar_post' post.id %}">Eliminar</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}
 

{% block footer %} 
{% include "partes/footer.html" %}
{%endblock%}

Blog/templates/perfiles/login.html
{% extends "base.html" %}
{% load static %}
{% block contenido %}
<h2>Iniciar sesión</h2>

<form method="post">
    {% csrf_token %}

    {% if form.non_field_errors %}
        <div style="color:red;">{{ form.non_field_errors }}</div>
    {% endif %}

    {% for field in form %}
        <div>
            {{ field.label_tag }}
            {{ field }}
            {% if field.errors %}
                <div style="color:red;">{{ field.errors }}</div>
            {% endif %}
        </div>
    {% endfor %}

    <button type="submit">Ingresar</button>
</form>
{% endblock %}

Blog/templates/perfiles/perfil.html
{% extends "base.html" %}
{% load static %}


{% block titulo %}
<title>Post</title>
{% endblock %}


{% block header %}
    {% include "partes/header.html" %}
{%endblock%}


{% block contenido %}
<div class="contenido">
    <style>
        .contenido{
            width: auto;
            height: 500px;
            background-color: #ff00c8ff;
        }
    </style>
</div>
{%endblock%}

{% block footer %}
    {% include "partes/footer.html" %}
{%endblock%}

Blog/templates/perfiles/registrarse.html
{% extends "base.html" %} 
{% load static %} 


{% block contenido %}
<h2>Crear cuenta</h2>

<form method="post">
  {% csrf_token %} {% if form.non_field_errors %}
  <div style="color: red">{{ form.non_field_errors }}</div>
  {% endif %} {% for field in form %}
  <div>
    {{ field.label_tag }} {{ field }} {% if field.errors %}
    <div style="color: red">{{ field.errors }}</div>
    {% endif %}
  </div>
  {% endfor %}

  <button type="submit">Registrarse</button>
</form>
{% endblock %}

Blog/templates/perfiles/usuario.html
{% extends "base.html" %}
{% load static %}


{% block titulo %}
<title>Usuario</title>
{% endblock %}


{% block header %}
    {% include "partes/header.html" %}
{%endblock%}


{% block contenido %}
<div class="contenido">
    <style>
        .contenido{
            width: auto;
            height: 500px;
            background-color: #3421dbff;
        }
    </style>
</div>
{%endblock%}

{% block footer %}
    {% include "partes/footer.html" %}
{%endblock%}