Blog/Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# Importa las vistas necesarias
from .views import index

urlpatterns = [
    # Rutas principales del proyecto
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    
    # Rutas de las aplicaciones
    path('post/', include('apps.Post.urls')),
    path('comentario/', include('apps.Comment.urls')),
    path('perfil/', include('apps.Perfiles.urls')),
]

# Configuración para servir archivos estáticos y de medios en desarrollo
# Asegúrate de que esto solo se ejecute cuando DEBUG sea True
if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

Blog/apps/Post/urls.py
from django.urls import path
from .views import CrearPost, ActualizarPost, EliminarPost, ListarPost , DetallarPost
from .views import AgregarGenero, ActualizarGenero, EliminarGenero
from .views import AgregarPlataforma, ActualizarPlataforma, EliminarPlataforma


app_name = 'post'

urlpatterns = [
    path("agregar_genero/", AgregarGenero.as_view(), name="agregar_genero"),
    path("actualizar_genero/", ActualizarGenero.as_view(), name="actualizar_genero"),
    path("eliminar_genero/", EliminarGenero.as_view(), name="eliminar_genero"),

    path("agregar_plataforma/", AgregarPlataforma.as_view(), name="agregar_plataforma"),
    path("actualizar_plataforma/", ActualizarPlataforma.as_view(), name="actualizar_plataforma"),
    path("eliminar_plataforma/", EliminarPlataforma.as_view(), name="eliminar_plataforma"),

    path('', ListarPost.as_view(),name='posts'),
    path('agregar/', CrearPost.as_view(),name='agregar_post'),
    path('actualizar/<int:pk>/', ActualizarPost.as_view(), name='actualizar_post'),
    path('eliminar/<int:pk>',EliminarPost.as_view(),name='eliminar_post'),
    path('<int:id>/',DetallarPost.as_view(),name='post_individual'),
]

Blog/templates/partes/footer.html
{% load static %}

<footer>
  <main>
    <h1>contacto</h1>

    <section class="pie" id="pie">
      <h1>contactate a traves de los siguientes enlaces</h1>
      <h2>correo@gmail.com</h2>
      <h2>mensaje como usuario</h2>
      <h3>creado por grupo 7, comision 5, Informatorio</h3>
    </section>
  </main>
</footer>

Blog/templates/partes/header.html
{% load static %}

<header class="encabezado" id="encabezado">
  <nav>
    <a class="navegacion__enlace" href="#inicio">
      <h2 class="navegacion__titulo">Principal</h2>
    </a>
    <ul class="enlaces">
      <li class="enlaces__item">
        <a class="enlaces__enlace" href="{% url 'index' %}">Inicio</a>
      </li>
      <li class="enlaces__item">
        <a class="enlaces__enlace" href="{% url "apps.Perfiles:login" %}">iniciar sesion</a>
      </li>
      <li class="enlaces__item">
        <a class="enlaces__enlace" href="{% url "apps.Perfiles:registrarse" %}">crear usuario</a>
      </li>
      <li class="enlaces__item">
        <a class="enlaces__enlace" href="{% url 'post:posts' %}">Posts</a>
      </li>


    </ul>
  </nav>
</header>